# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "a.kin.bo"
description:        "a web journal by Tim Akinbo"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//a.kin.bo"
author:             "takinbo"
twitter:
  username:         "takinbo"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:title/

# Markdown
markdown:           kramdown

exclude:            ["css/", "README.md"]

# Sass
sass:
  style:            :compressed

# Navigation
nav:
  - name:           "twitter"
    href:           "https://twitter.com/takinbo"
  - name:           "github"
    href:           "https://github.com/takinbo"
  - name:           "rss"
    href:           "/feed.xml"

compress_html:
  comments:         ["<!-- ", " -->"]
  clippings:        all
  endings:          all
  startings:        all

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      author:       "takinbo"

gems:
  - jekyll-seo-tag

